### ISSUE TITLE
Display of device dimensions is incorrect in device view

### ISSUE THREAD

**Issue by ahgough** [UPDDI/mps-web-client#49]
When viewing a device in the web client, the dimensions are displayed as w x w x thickness instead of w x l x thickness.  For example, Liver Acinus Device v1.1 is configured as 2 x 6 x 0.2, but dimensions in the View are 2.0 mm x 2.0 mm x 0.2 mm.

**Comment by Luke-Malchow-Bergenthal** [comment]
Sure enough, width is listed twice. A very ugly bug. Thanks for the catch.

**Comment by Luke-Malchow-Bergenthal** [comment]
Fix deployed as of https://github.com/UPDDI/mps-database-server/commit/f7f5dec7e8170dfb1a7cbefb8e21d0b38d2c82fd. Thank you for your assistance.
