### ISSUE TITLE
Project Filters Should Respond to the User's Groups

### ISSUE THREAD

**Issue by ahgough** [UPDDI/mps-web-client#50]
When I filter compounds, say be deselecting Show MPS and Show TCTC, there are 68 compounds in the list. If I view one, then come back to the list with the back arrow, the filters are still shown (i.e. Show MPS and Show TCTC are still unselected, but the whole list of 372 compounds is shown. This could be misleading. I understand the problem with returning to a page with a selection, however, if I refresh the page, the filter selections go back to the default of all selected, and then at least the page is consistent. Is there a way to refresh the page on return as a quick solution to this problem? Can we make the default filter setting Group specific (i.e. if I am in Taylor_EPA, only Show EPA is selected)?

**Comment by Luke-Malchow-Bergenthal** [comment]
Related: https://github.com/UPDDI/mps-database-server/issues/385

The bug where filters are incorrectly applied should be fixed on stage, but it looks I will have to make some more fixes before merging into master.

I will look into changing the filters automatically depending on the chosen group, but in order for that to work we must either include a designation (like 'EPA') in the group names or have some other way of indicating what filters to use.

**Comment by ahgough** [comment]
I think we can make sure the EPA group names include ‘_EPA’ and the TCTC group names include ‘_TCTC’.

-Bert

**Comment by Luke-Malchow-Bergenthal** [comment]
Old issue, but I will note that Project associations are now deprecated regardless.
